### ISSUE TITLE
Urdu Artificial Text Detection: Train and evaluate a CNN to detect presence of Urdu Text on the screen. Briefly mention if the CNN is a valid family of models to use for this task with your reasoning.

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#12]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by ank426** [comment]
I would like to work on this task. We can use object localization using a simple CNN or a ResNet.
