### ISSUE TITLE
American Sign Language: Plot a graph to visualize the class distribution and analyze if there is class imbalance in the data. Handle the imbalance and mention your approach for the same.

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#13]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by syed-hamza** [comment]
* [x]  Hacktober Fest Contributor
 
Use a simple bar plot to figure out class imbalance
sort the frequencies of respective classes and then use a mix of data augmentation and under-sampling to fix the issue
