### ISSUE TITLE
American Sign Language: Train and evaluate a classification model for the data. Provide performance plots of your model and explain your inductive bias. 

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#14]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by ank426** [comment]
I'd like to work on this. Can use a CNN.

**Comment by Bhav-Hub** [comment]
A simple CNN model to classify the images or we can use a live object detection model using the camera to feed data and show the corresponding labels in real time
