### ISSUE TITLE
American Sign Language : Perform a comparison study between various classification deep learning and machine learning models. Provide a tabular result with the performance metrics as well as performance plots for the various models chosen.

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#15]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by syed-hamza** [comment]
i will show a comparison between accuracy and loss with VGG, InceptionV3,inceptionresnet and mobile net and update the models. issue beku
