### ISSUE TITLE
Yahoo Answers : Perform Exploratory Data Analysis and explain your understanding of the problem at hand. Provide a plot which shows the class distribution in the dataset and suggest any precautionary measure that can be taken to explain your model's performance

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#16]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by syed-hamza** [comment]
textbook data analysis-> bar plots for class distribution-> precautionary measures post analysis
