### ISSUE TITLE
Yahoo Answers: Train a BERT Sequence Model for predicting the "best_answer" target variable. Suggest any evaluation metrics that could be used for this task with your reasoning.

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#18]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by amulyamarali** [comment]
Evaluatoin metrics that could be used is F1 score, cuz especially for question answer type models its important to asses the predicted answer based on the ground truth values. 

But need to train the model first :)

**Comment by amulyamarali** [comment]
- [ ]  Hacktober Fest Contributor

Could use F1 score to asses the predicted answers based on the groud truth values. especially for question anwer models.

But need to train the model first :)

**Comment by amulyamarali** [comment]
Field Description
About using BERT model for predicting the "best answer"
Github [amulyamarali](https://github.com/amulyamarali)
Email [here](mailto:maraliamulya)
Label Update request
Define You


- [ ]  Hacktober Fest Contributor

Describe the solution you'd like...
Could use F1 score to asses the predicted answers based on the groud truth values. especially for question anwer models.

Approach to be followed (optional):
First the model has to be created using BERT

I would like to work on this task , request to assign it to me.
Thanks
