### ISSUE TITLE
Bank Approval Prediction : Perform EDA to understand the class distribution and correlation between various attributes. (Multiple Correlation techniques might be required)

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#6]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by aaryanhb** [comment]
> Field	Description
> About	EDA for UniversalBank Dataset to understand the data.
> Github	aaryanhb
> Email	aaryanhb003@gmail.com
> Label	Update request
> **Define You**
> 
> * [ ]  Hacktober Fest Contributor
> 
> 
> **Describe the solution you'd like...**
> Using different correlation analysis between pairs of variables.
> 
> **Approach to be followed (optional):**
> Could use spearman rank , pearson coeeficient, point bi-serial , etc for different types of variables. (ordinal,nominal,ratio)

I would like to work on this task , request to assign it to me.
Thanks
