### ISSUE TITLE
Amazon Reviews Sentiment Analysis: Clean and prepare the dataset by following practices such as removing stop-words, non alphanumeric characters etc.

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#8]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by saqlain2204** [comment]
Solution: Data contains stop words that have no direct correlation with sentiment. Non-numeric characters play a minimal role in a text-dominated review. To improve the data quality, it's advisable to remove emojis, normalize alphabet casing, and delete extra spaces etc.
I would like to work on this issue. Can you assign it to me
