### ISSUE TITLE
Amazon Reviews Sentiment Analysis: Train and evaluate a RandomForestClassifier with the 'score-poz-neg' column as the target attribute.

### ISSUE THREAD

**Issue by akash-kamalesh** [dscpesu/SimpleML#9]
---

| Field  | Description                       |
| ------ | --------------------------------- |
| About  | A short Description about project |
| Github | Your Github name                  |
| Email  |                                   |
| Label  | Update request                    |

---

**Define You**

- [ ] Hacktober Fest Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by kganeshv12** [comment]
> Field	Description
> About	A short Description about project
> Github	Your Github name
> Email	
> Label	Update request
> **Define You**
> 
> * [ ]  Hacktober Fest Contributor
> 
> **Is your feature request related to a problem? Please describe.**
> 
> **Describe the solution you'd like...**
> 
> **Describe alternatives you've considered?**
> 
> **Approach to be followed (optional):**
> 
> **Additional context**

I am interested to work on this issue, please do assign it to me.
We convert the text into numerical features using embedding techniques.
As mentioned, we will be using the RandomForestClassifier model to predict the 'score-poz-neg' column.
